# Generated by Django 3.2.6 on 2021-08-30 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='serial_number',
            field=models.IntegerField(),
        ),
    ]
